name: python-application.yml

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1. Descargar el código fuente
    - name: Descargar codigo fuente
      uses: actions/checkout@v4

    # Configurar entorno de Python
    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # 2. Instalar dependencias
    - name: Instalar dependencias
      run: |
        python -minstalled pip --upgrade pip
        pip install -r requirements.txt

    # 3. Ejecutar pruebas automatizadas
    - name: Ejecutar pruebas automatizadas
      run: |
        pytest

    # 4. Ejecutar la aplicación
    - name: Ejecutar la aplicacion
      run: |
        python app/calculadora.py

    # 5. Simular una fase de despliegue
    - name: Simular fase de despliegue
      run: |
        echo "Iniciando el despliegue simulado..."
        echo "Verificando artefactos y entorno..."
        echo "Despliegue simulado con exito en el entorno de Staging."

  deploy-docker:
    runs-on: ubuntu-latest
    needs: build-and-test # Solo se ejecuta si las pruebas pasan
    permissions:
      contents: read
      packages: write

    steps:
    - name: Descargar codigo fuente
      uses: actions/checkout@v4

    # 7. Autenticarse en GitHub Container Registry
    - name: Autenticarse en GitHub Container Registry (GHCR)
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # 6 y 8. Construir y Publicar la imagen Docker de manera simplificada
    - name: Construir y Publicar imagen Docker
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ghcr.io/kamsantana/ejercicio:3.0.0